### ISSUE TITLE
RoadMap for 1.0

### ISSUE THREAD

**Issue by chaokunyang** [apache/fory#1017]
- Format Specification
  - #1239
  - #1413 
  - Row format documentation
- Java 
  - Object Graph
    - #925
    - #203
    - #202
  - Row Format
    - #2931
- Python
  - [x] Support Collection/Map V2 protocol
  - [x] Cross-language schema compatibility for object graph.
    - https://github.com/apache/fory/pull/2509
    - https://github.com/apache/fory/pull/2593
    - https://github.com/apache/fory/pull/2602
  - Performance optimization for cython
- JavaScript
  - Cross-language schema compatibility for object graph.
  - Support Collection/Map V2 protocol
- C++
  - C++ serialization:
    - C++ object graph serialization support: https://github.com/apache/fory/pull/2908
    - C++ xlang serialization: https://github.com/apache/fory/pull/2925
    - #2943
    - #2944
    - #2959
    - #2960
    - #2966
    - #2958 
    - #3088
    - #2906 
  - C++ Row format:
    - https://github.com/apache/fory/pull/1144
    - #1145
  - Support both bazel and cmake: #2921
- Golang
  - Codegen Framework for golang to generate code statically.
  - [x] Support Collection/Map V2 protocol
  - [x] Cross-language schema compatibility for object graph.
  - [x] #2998 
  - [x] #3063
  - [x] #3069 
  - [ ] #2982 
- Rust
  - https://github.com/apache/fory/pull/2774
  - https://github.com/apache/fory/pull/2778
  - [x] Support Collection/Map V2 protocol
  - #1190
  - [x] Support trait object polymorphism serialization
    - #2691 
    - #2704
  - Shared reference tracking for `Rc/Arc`:
    - #2678
    - #2707 
    - #2679 
  - [x] Cross-language schema compatibility for object graph.
    - #2492
    - #2545 
    - #2758
  - Detailed API and user document: https://github.com/apache/fory/pull/2728 
  - #3089
- #1197

**Comment by zqr10159** [comment]
Hi team,

First of all, thank you for your hard work on this project; it looks very promising.

I am writing to inquire about the current status of the Go implementation. Could you please share any updates on when we might expect a release that includes full XLANG support? I didn't see it in the documentation.

Thanks in advance for your time and help!

**Comment by chaokunyang** [comment]
Hi @zqr10159 , thanks for the question and for your interest in the project!

Right now, the Go serialization implementation is still in progress. We’ve recently finished the Rust, C++, and Python serialization, and Go is next on the list. If everything goes smoothly, we expect to have a feature‑complete Go release with full XLANG support in the near future.

We’ll update the documentation and roadmap as soon as we have a clearer timeline. Thanks again for your patience and support!

**Comment by zqr10159** [comment]
> Hi [@zqr10159](https://github.com/zqr10159) , thanks for the question and for your interest in the project!
> 
> Right now, the Go serialization implementation is still in progress. We’ve recently finished the Rust, C++, and Python serialization, and Go is next on the list. If everything goes smoothly, we expect to have a feature‑complete Go release with full XLANG support in the near future.
> 
> We’ll update the documentation and roadmap as soon as we have a clearer timeline. Thanks again for your patience and support!

Thanks for the info! Really looking forward to the Go support. Best of luck with the development!

**Comment by chaokunyang** [comment]
> Thanks for the info! Really looking forward to the Go support. Best of luck with the development!

Hi @zqr10159 , Apache Fory Go Serialization has been released in 0.15.0, you can use it now. See https://fory.apache.org/blog/fory_0_15_0_release/ for more details

**Comment by zqr10159** [comment]
> > Thanks for the info! Really looking forward to the Go support. Best of luck with the development!
> 
> Hi [@zqr10159](https://github.com/zqr10159) , Apache Fory Go Serialization has been released in 0.15.0, you can use it now. See https://fory.apache.org/blog/fory_0_15_0_release/ for more details

Thank you for your support!
